-- 코드를 입력하세요
SELECT t1.NAME, t1.DATETIME
FROM ANIMAL_INS AS t1
LEFT JOIN ANIMAL_OUTS AS t2 # 왼쪽 테이블에만 존재하는것 출력
    ON t1.ANIMAL_ID = t2.ANIMAL_ID
WHERE t2.DATETIME IS NULL AND t1.DATETIME IS NOT NULL
ORDER BY t1.DATETIME
LIMIT 3;