-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES 
FROM PRODUCT AS t1
INNER JOIN OFFLINE_SALE AS t2
    ON t1.PRODUCT_ID = t2.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;